
tasks:
  - init: npm install && npm run build
    command: npm run start



vscode:
  extensions:
    - bierner.markdown-preview-github-stylesle)
# and commit this file to your remote git repository to share the goodness with others.

tasks:
  - init: npm install && npm run build
    command: npm run start


