# swizzle for v2.1.0
npm run swizzle @docusaurus/theme-classic CodeBlock -- --danger --wrap
npm run swizzle @docusaurus/theme-classic ColorModeToggle -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocCardList -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/Copyright -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/Layout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/LinkItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/Links -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/Links/MultiColumn -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/Links/Simple -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Footer/Logo -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/Arrow -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/DarkMode -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/Edit -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/LightMode -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/Menu -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/A -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Code -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Details -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Heading -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Img -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Pre -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Ul -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXContent -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NotFound -- --danger --wrap
npm run swizzle @docusaurus/theme-classic SearchBar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Admonition -- --danger --wrap
npm run swizzle @docusaurus/theme-classic AnnouncementBar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic AnnouncementBar/CloseButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic AnnouncementBar/Content -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BackToTopButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogArchivePage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogLayout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogListPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogListPaginator -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Container -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Content -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Footer -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Footer/ReadMoreLink -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Header -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Header/Author -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Header/Authors -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Header/Info -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItem/Header/Title -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostItems -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostPage/Metadata -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogPostPaginator -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogSidebar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogSidebar/Desktop -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogSidebar/Mobile -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogTagsListPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic BlogTagsPostsPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/Container -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/Content -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/Content/Element -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/Content/String -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/CopyButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/Line -- --danger --wrap
npm run swizzle @docusaurus/theme-classic CodeBlock/WordWrapButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Details -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocBreadcrumbs -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocCard -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocCategoryGeneratedIndexPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/Content -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/Footer -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/Layout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/Metadata -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/Paginator -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/TOC -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/TOC/Desktop -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocItem/TOC/Mobile -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocPage/Layout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocPage/Layout/Main -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocPage/Layout/Sidebar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocPage/Layout/Sidebar/ExpandButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocPaginator -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebar/Desktop -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebar/Desktop/CollapseButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebar/Desktop/Content -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebar/Mobile -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebarItem/Category -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebarItem/Html -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebarItem/Link -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocSidebarItems -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocTagDocListPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocTagsListPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocVersionBadge -- --danger --wrap
npm run swizzle @docusaurus/theme-classic DocVersionBanner -- --danger --wrap
npm run swizzle @docusaurus/theme-classic EditThisPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic ErrorPageContent -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Heading -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/Close -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/ExternalLink -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/Home -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Icon/Language -- --danger --wrap
npm run swizzle @docusaurus/theme-classic LastUpdated -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Layout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Layout/Provider -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Logo -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXComponents/Head -- --danger --wrap
npm run swizzle @docusaurus/theme-classic MDXPage -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/ColorModeToggle -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/Content -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/Layout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/Logo -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/MobileSidebar -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/MobileSidebar/Header -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/MobileSidebar/Layout -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/MobileSidebar/PrimaryMenu -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/MobileSidebar/SecondaryMenu -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/MobileSidebar/Toggle -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Navbar/Search -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/DefaultNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/DocNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/DocSidebarNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/DocsVersionDropdownNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/DocsVersionNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/DropdownNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/HtmlNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/LocaleDropdownNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/NavbarNavLink -- --danger --wrap
npm run swizzle @docusaurus/theme-classic NavbarItem/SearchNavbarItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic PaginatorNavLink -- --danger --wrap
npm run swizzle @docusaurus/theme-classic SearchMetadata -- --danger --wrap
npm run swizzle @docusaurus/theme-classic SiteMetadata -- --danger --wrap
npm run swizzle @docusaurus/theme-classic SkipToContent -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TOC -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TOCCollapsible -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TOCCollapsible/CollapseButton -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TOCInline -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TOCItems -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TOCItems/Tree -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TabItem -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Tabs -- --danger --wrap
npm run swizzle @docusaurus/theme-classic Tag -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TagsListByLetter -- --danger --wrap
npm run swizzle @docusaurus/theme-classic TagsListInline -- --danger --wrap
npm run swizzle @docusaurus/theme-classic ThemedImage -- --danger --wrap